### ISSUE TITLE
Facebook monkeypatch urllib

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#88]
url: /unauthenticated/mobi/registration/register_facebook
function: #rogerthat.bizz.profile._couple_facebook_id_with_profile

```python
09:28:02.921
/base/data/home/apps/s~mobicagecloudhr/9.399000778755475790/lib/requests-2.13.0.zip/requests/packages/urllib3/contrib/appengine.py:115: AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets. To use sockets directly instead of URLFetch see https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html.
```

**Comment by abom** [comment]
This is not a bug, it's a warning from urllib3 that it can use sockets instead of urlfetch with GAE.

As the monkey patching is done by requests-toolbelt, which uses [urllib3 AppEngineManager](https://github.com/sigmavirus24/requests-toolbelt/blob/24586406ad59783666d35a435e2e67f6fece0f1a/requests_toolbelt/adapters/appengine.py#L109) not PoolManager, i think that we cannot use sockets?

**Comment by RubenMattan** [comment]
On the prod server this is an error!
Maybe because the path is not covered by the monkeypatch...

**Comment by abom** [comment]
@RubenMattan Sorry Ruben, i tested it on the local environment.

**Comment by RubenMattan** [comment]
Copy abom

I think we can filter the AppEnginePlatformWarning using warnings filtering in python warning lib
https://docs.python.org/2/library/warnings.html#the-warnings-filter
